include $(shell rospack find mk)/cmake.mk

all: export

export:
	mkdir -p include/multires_image
	cp src/libtile_cache/*.h include/multires_image
	cp src/libmultires_widget/*.h include/multires_image
