set(_CATKIN_CURRENT_PACKAGE "mapviz")
set(mapviz_VERSION "0.2.5")
set(mapviz_MAINTAINER "Marc Alban <malban@swri.org>")
set(mapviz_PACKAGE_FORMAT "2")
set(mapviz_BUILD_DEPENDS "message_generation" "drones4life_scenario" "libqt5-opengl-dev" "cv_bridge" "glut" "image_transport" "libglew-dev" "libqt5-core" "libqt5-gui" "libqt5-opengl" "libqt5-widgets" "libxi-dev" "libxmu-dev" "marti_common_msgs" "pluginlib" "rosapi" "roscpp" "rqt_gui_cpp" "rqt_gui" "std_srvs" "swri_transform_util" "swri_yaml_util" "tf")
set(mapviz_BUILD_EXPORT_DEPENDS "cv_bridge" "glut" "image_transport" "libglew-dev" "libqt5-core" "libqt5-gui" "libqt5-opengl" "libqt5-widgets" "libxi-dev" "libxmu-dev" "marti_common_msgs" "pluginlib" "rosapi" "roscpp" "rqt_gui_cpp" "rqt_gui" "std_srvs" "swri_transform_util" "swri_yaml_util" "tf")
set(mapviz_BUILDTOOL_DEPENDS "catkin" "pkg-config")
set(mapviz_BUILDTOOL_EXPORT_DEPENDS )
set(mapviz_EXEC_DEPENDS "message_runtime" "cv_bridge" "glut" "image_transport" "libglew-dev" "libqt5-core" "libqt5-gui" "libqt5-opengl" "libqt5-widgets" "libxi-dev" "libxmu-dev" "marti_common_msgs" "pluginlib" "rosapi" "roscpp" "rqt_gui_cpp" "rqt_gui" "std_srvs" "swri_transform_util" "swri_yaml_util" "tf")
set(mapviz_RUN_DEPENDS "message_runtime" "cv_bridge" "glut" "image_transport" "libglew-dev" "libqt5-core" "libqt5-gui" "libqt5-opengl" "libqt5-widgets" "libxi-dev" "libxmu-dev" "marti_common_msgs" "pluginlib" "rosapi" "roscpp" "rqt_gui_cpp" "rqt_gui" "std_srvs" "swri_transform_util" "swri_yaml_util" "tf")
set(mapviz_TEST_DEPENDS )
set(mapviz_DOC_DEPENDS )
set(mapviz_URL_WEBSITE "https://github.com/swri-robotics/mapviz")
set(mapviz_URL_BUGTRACKER "")
set(mapviz_URL_REPOSITORY "")
set(mapviz_DEPRECATED "")