set(_CATKIN_CURRENT_PACKAGE "mapviz_plugins")
set(mapviz_plugins_VERSION "0.2.5")
set(mapviz_plugins_MAINTAINER "Marc Alban <malban@swri.org>")
set(mapviz_plugins_PACKAGE_FORMAT "2")
set(mapviz_plugins_BUILD_DEPENDS "libqt5-opengl-dev" "message_generation" "actionlib" "cv_bridge" "gps_common" "image_transport" "libqt5-core" "libqt5-gui" "libqt5-opengl" "libqt5-widgets" "mapviz" "marti_common_msgs" "marti_nav_msgs" "marti_visualization_msgs" "move_base_msgs" "nav_msgs" "pluginlib" "roscpp" "sensor_msgs" "std_msgs" "stereo_msgs" "swri_image_util" "swri_math_util" "swri_route_util" "swri_transform_util" "swri_yaml_util" "tf" "visualization_msgs")
set(mapviz_plugins_BUILD_EXPORT_DEPENDS "message_runtime" "actionlib" "cv_bridge" "gps_common" "image_transport" "libqt5-core" "libqt5-gui" "libqt5-opengl" "libqt5-widgets" "mapviz" "marti_common_msgs" "marti_nav_msgs" "marti_visualization_msgs" "move_base_msgs" "nav_msgs" "pluginlib" "roscpp" "sensor_msgs" "std_msgs" "stereo_msgs" "swri_image_util" "swri_math_util" "swri_route_util" "swri_transform_util" "swri_yaml_util" "tf" "visualization_msgs")
set(mapviz_plugins_BUILDTOOL_DEPENDS "catkin")
set(mapviz_plugins_BUILDTOOL_EXPORT_DEPENDS )
set(mapviz_plugins_EXEC_DEPENDS "message_runtime" "actionlib" "cv_bridge" "gps_common" "image_transport" "libqt5-core" "libqt5-gui" "libqt5-opengl" "libqt5-widgets" "mapviz" "marti_common_msgs" "marti_nav_msgs" "marti_visualization_msgs" "move_base_msgs" "nav_msgs" "pluginlib" "roscpp" "sensor_msgs" "std_msgs" "stereo_msgs" "swri_image_util" "swri_math_util" "swri_route_util" "swri_transform_util" "swri_yaml_util" "tf" "visualization_msgs")
set(mapviz_plugins_RUN_DEPENDS "message_runtime" "actionlib" "cv_bridge" "gps_common" "image_transport" "libqt5-core" "libqt5-gui" "libqt5-opengl" "libqt5-widgets" "mapviz" "marti_common_msgs" "marti_nav_msgs" "marti_visualization_msgs" "move_base_msgs" "nav_msgs" "pluginlib" "roscpp" "sensor_msgs" "std_msgs" "stereo_msgs" "swri_image_util" "swri_math_util" "swri_route_util" "swri_transform_util" "swri_yaml_util" "tf" "visualization_msgs")
set(mapviz_plugins_TEST_DEPENDS )
set(mapviz_plugins_DOC_DEPENDS )
set(mapviz_plugins_URL_WEBSITE "https://github.com/swri-robotics/mapviz")
set(mapviz_plugins_URL_BUGTRACKER "")
set(mapviz_plugins_URL_REPOSITORY "")
set(mapviz_plugins_DEPRECATED "")