// *****************************************************************************
//
// Copyright (c) 2017, Southwest Research Institute® (SwRI®)
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of Southwest Research Institute® (SwRI®) nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// *****************************************************************************

#ifndef MAPVIZ_PLUGINS__MOVE_BASE_PLUGIN_HPP_
#define MAPVIZ_PLUGINS__MOVE_BASE_PLUGIN_HPP_

// C++ standard libraries
#include <string>

#include <mapviz/mapviz_plugin.hpp>

// QT libraries
#include <QOpenGLFunctions_1_1>
#include <QOpenGLWidget>
#include <QObject>
#include <QTimer>
#include <QWidget>

// ROS libraries
#include <rclcpp/rclcpp.hpp>
#include <rclcpp_action/rclcpp_action.hpp>

// Mapviz libraries
#include <mapviz/map_canvas.hpp>

#include <geometry_msgs/msg/pose_with_covariance_stamped.hpp>
#include <nav2_msgs/action/navigate_to_pose.hpp>

// QT autogenerated files
#include "ui_move_base_config.h"

namespace mapviz_plugins
{
  class MoveBasePlugin : public mapviz::MapvizPlugin, protected QOpenGLFunctions_1_1
  {
    Q_OBJECT

   public:
    using NavigateToPose = nav2_msgs::action::NavigateToPose;
    using GoalHandle = rclcpp_action::ClientGoalHandle<NavigateToPose>;

    MoveBasePlugin();
    ~MoveBasePlugin() override;

    bool Initialize(QOpenGLWidget* canvas) override;
    void Shutdown() override {}

    QWidget* GetConfigWidget(QWidget* parent) override;

   protected:
    void Draw(double x, double y, double scale) override;
    void Paint(QPainter* /*painter*/, double /*x*/, double /*y*/, double /*scale*/) override {}
    void Transform() override {}

    void LoadConfig(const YAML::Node& node, const std::string& path) override;
    void SaveConfig(YAML::Emitter& emitter, const std::string& path) override;

    void PrintError(const std::string& message) override;
    void PrintInfo(const std::string& message) override;
    void PrintWarning(const std::string& message) override;
    bool eventFilter(QObject* object, QEvent* event) override;

    bool handleMousePress(QMouseEvent*);
    bool handleMouseRelease(QMouseEvent*);
    bool handleMouseMove(QMouseEvent*);

   Q_SIGNALS:
    // Emitted from the ROS spin thread by the action-client callbacks;
    // delivered to handleActionStatus() as a queued connection on the GUI
    // thread, which owns action_status_ and the widgets.
    void ActionStatusChanged(int status);

   private Q_SLOTS:
    void on_pushButtonInitialPose_toggled(bool checked);
    void on_pushButtonGoalPose_toggled(bool checked);
    void on_pushButtonAbort_clicked();

    // Runs on the GUI thread (QTimer::timeout); polls server connectivity and
    // reflects the latest goal status in the status label.
    void timerCallback();
    void handleActionStatus(int status);

   private:
    // Lifecycle of the most recently sent navigation goal.  Owned by the GUI
    // thread; updated only through handleActionStatus().
    enum ActionStatus
    {
      IDLE,
      ACTIVE,
      SUCCEEDED,
      ABORTED,
      REJECTED,
      CANCELED
    };

    Ui::move_base_config ui_;
    QWidget* config_widget_;
    mapviz::MapCanvas* map_canvas_;

    rclcpp::Publisher<geometry_msgs::msg::PoseWithCovarianceStamped>::SharedPtr init_pose_pub_;
    rclcpp_action::Client<NavigateToPose>::SharedPtr move_base_client_;

    QTimer timer_;
    ActionStatus action_status_;

    bool is_mouse_down_;
    QPointF arrow_tail_position_;
    float arrow_angle_;
  };
}   // namespace mapviz_plugins

#endif  // MAPVIZ_PLUGINS__MOVE_BASE_PLUGIN_HPP_
