// *****************************************************************************
//
// Copyright (C) 2013 All Right Reserved, Southwest Research Institute® (SwRI®)
//
// Contract No.  10-58058A
// Contractor    Southwest Research Institute® (SwRI®)
// Address       6220 Culebra Road, San Antonio, Texas 78228-0510
// Contact       Steve Dellenback <sdellenback@swri.org> (210) 522-3914
//
// This code was developed as part of an internal research project fully funded
// by Southwest Research Institute®.
//
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// *****************************************************************************

#ifndef MULTIRES_IMAGE_PLUGIN_H
#define MULTIRES_IMAGE_PLUGIN_H

// C++ standard libraries
#include <string>

// Boost libraries
#define BOOST_FILESYSTEM_VERSION 2
#include <boost/filesystem.hpp>

// QT libraries
#include <QGLWidget>
#include <QObject>
#include <QWidget>

#include <transform_util/transform.h>
#include <transform_util/transform_manager.h>
#include <mapviz/mapviz_plugin.h>
#include <mapviz/map_canvas.h>
#include <multires_image/tile_set.h>

#include <mapviz_plugins/multires_view.h>

// QT autogenerated files
#include "ui_multires_config.h"

namespace mapviz_plugins
{

  class MultiresImagePlugin : public mapviz::MapvizPlugin
  {

    Q_OBJECT

  public:

    MultiresImagePlugin();
    virtual ~MultiresImagePlugin();

    bool Initialize(QGLWidget* canvas);
    void Shutdown() {}

    void Draw(double x, double y, double scale);

    void Transform();

    void LoadConfiguration(const YAML::Node& node, const std::string& config_path);
    void SaveConfiguration(YAML::Emitter& emitter, const std::string& config_path);

    QWidget* GetConfigWidget(QWidget* parent);

  protected:
    void PrintError(const std::string& message);
    void PrintInfo(const std::string& message);
    void PrintWarning(const std::string& message);

  protected Q_SLOTS:
    void SelectFile();
    void AcceptConfiguration();

  private:
    bool     loaded_;
    double center_x_;
    double center_y_;

    multires_image::TileSet* tile_set_;
    MultiresView* tile_view_;

    Ui::multires_config ui_;
    QWidget* config_widget_;

    transform_util::TransformManager transform_manager_;
    transform_util::Transform transform_;
    transform_util::Transform inverse_transform_;

    bool transformed_;

    void GetCenterPoint(double x, double y);
    boost::filesystem::path MakePathRelative(boost::filesystem::path path, boost::filesystem::path base);
  };
}

#endif /* MULTIRES_IMAGE_PLUGIN_H */
