// *****************************************************************************
//
// Copyright (C) 2013 All Right Reserved, Southwest Research Institute® (SwRI®)
//
// Contract No.  10-58058A
// Contractor    Southwest Research Institute® (SwRI®)
// Address       6220 Culebra Road, San Antonio, Texas 78228-0510
// Contact       Steve Dellenback <sdellenback@swri.org> (210) 522-3914
//
// This code was developed as part of an internal research project fully funded
// by Southwest Research Institute®.
//
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// *****************************************************************************

#ifndef MAPVIZ_PLUGINS_ROBOT_IMAGE_PLUGIN_H_
#define MAPVIZ_PLUGINS_ROBOT_IMAGE_PLUGIN_H_

// C++ standard libraries
#include <string>

// QT libraries
#include <QGLWidget>
#include <QObject>
#include <QWidget>

// ROS libraries
#include <ros/ros.h>
#include <tf/transform_datatypes.h>

#include <mapviz/mapviz_plugin.h>
#include <mapviz/map_canvas.h>

// QT autogenerated files
#include "ui_robot_image_config.h"
#include "ui_topic_select.h"

namespace mapviz_plugins
{
  class RobotImagePlugin : public mapviz::MapvizPlugin
  {
    Q_OBJECT

  public:
    RobotImagePlugin();
    virtual ~RobotImagePlugin();

    bool Initialize(QGLWidget* canvas);
    void Shutdown() {}

    void Draw(double x, double y, double scale);

    void Transform();

    void LoadConfig(const YAML::Node& node, const std::string& path);
    void SaveConfig(YAML::Emitter& emitter, const std::string& path);

    QWidget* GetConfigWidget(QWidget* parent);

  protected:
    void PrintError(const std::string& message);
    void PrintInfo(const std::string& message);
    void PrintWarning(const std::string& message);

  protected Q_SLOTS:
    void SelectFile();
    void SelectFrame();
    void FrameEdited();
    void WidthChanged(double value);
    void HeightChanged(double value);

  private:
    Ui::robot_image_config ui_;
    QWidget* config_widget_;

    double width_;
    double height_;

    std::string filename_;
    QImage      image_;
    int dimension_;
    int texture_id_;
    bool texture_loaded_;

    bool transformed_;

    tf::Point top_left_;
    tf::Point top_right_;
    tf::Point bottom_left_;
    tf::Point bottom_right_;

    tf::Point top_left_transformed_;
    tf::Point top_right_transformed_;
    tf::Point bottom_left_transformed_;
    tf::Point bottom_right_transformed_;

    void UpdateShape();
    void LoadImage();
  };
}

#endif  // MAPVIZ_PLUGINS_ROBOT_IMAGE_PLUGIN_H_
