// *****************************************************************************
//
// Copyright (c) 2026, Southwest Research Institute® (SwRI®)
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of Southwest Research Institute® (SwRI®) nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// *****************************************************************************

#ifndef MAPVIZ_PLUGINS__SPEEDOMETER_PLUGIN_HPP_
#define MAPVIZ_PLUGINS__SPEEDOMETER_PLUGIN_HPP_

#include <mapviz/mapviz_plugin.hpp>
#include <mapviz_plugins/placeable_window_proxy.hpp>

// QT libraries
#include <QObject>
#include <QWidget>

// ROS libraries
#include <rclcpp/rclcpp.hpp>
#include <nav_msgs/msg/odometry.hpp>

// C++ standard libraries
#include <string>

// QT autogenerated files
#include "ui_speedometer_config.h"

namespace mapviz_plugins
{
/**
 * Draws a dial showing the speed reported by a nav_msgs/Odometry topic, so the
 * vehicle's speed is visible without echoing the topic by hand.
 *
 * The dial is drawn with QPainter rather than immediate mode OpenGL because it
 * needs a numeric readout alongside the needle.
 */
class SpeedometerPlugin : public mapviz::MapvizPlugin
{
  Q_OBJECT

  public:
  SpeedometerPlugin();
  ~SpeedometerPlugin() override = default;

  bool Initialize(QOpenGLWidget* canvas) override;
  void Shutdown() override;

  QWidget* GetConfigWidget(QWidget* parent) override;

  protected:
  void Paint(QPainter* painter, double x, double y, double scale) override;

  void Draw(double, double, double) override {}

  void Transform() override {}

  void LoadConfig(const YAML::Node& node, const std::string& path) override;

  void SaveConfig(YAML::Emitter& emitter, const std::string& path) override;

  void PrintError(const std::string& message) override;
  void PrintInfo(const std::string& message) override;
  void PrintWarning(const std::string& message) override;

  protected Q_SLOTS:
  void SelectTopic();
  void TopicEdited();
  void MaxSpeedChanged(double value);

  private:
  // Called on the GUI thread by Subscribe(); owns all plugin state.
  void handleOdometry(const nav_msgs::msg::Odometry::ConstSharedPtr odometry);
  void connectCallback(const std::string& topic, const rmw_qos_profile_t& qos);

  /// Renders the dial into the placer's rectangle.
  void PaintDial(QPainter* painter, const QRectF& rect);

  Ui::speedometer_config ui_{};
  QWidget* config_widget_;

  PlaceableWindowProxy placer_;

  std::string topic_;
  rmw_qos_profile_t qos_;
  rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr odom_sub_;

  /// Magnitude of the most recent twist, in metres per second.
  double speed_;
  bool has_message_;

  /// Speed at the top of the dial, from the config widget.
  double max_speed_;
};
}   // namespace mapviz_plugins

#endif  // MAPVIZ_PLUGINS__SPEEDOMETER_PLUGIN_HPP_
