// *****************************************************************************
//
// Copyright (C) 2014 All Right Reserved, Southwest Research Institute® (SwRI®)
//
// Contract No.  10-58058A
// Contractor    Southwest Research Institute® (SwRI®)
// Address       6220 Culebra Road, San Antonio, Texas 78228-0510
// Contact       Steve Dellenback <sdellenback@swri.org> (210) 522-3914
//
// This code was developed as part of an internal research project fully funded
// by Southwest Research Institute®.
//
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// *****************************************************************************

#ifndef MAPVIZ_PLUGINS_TEXTURED_MARKER_PLUGIN_H_
#define MAPVIZ_PLUGINS_TEXTURED_MARKER_PLUGIN_H_

// C++ standard libraries
#include <string>
#include <list>
#include <map>

// QT libraries
#include <QGLWidget>
#include <QObject>
#include <QWidget>
#include <QColor>

#include <opencv2/core/core.hpp>

// ROS libraries
#include <ros/ros.h>
#include <tf/transform_datatypes.h>
#include <marti_visualization_msgs/TexturedMarker.h>
#include <marti_visualization_msgs/TexturedMarkerArray.h>

#include <GL/glut.h>
#include <mapviz/mapviz_plugin.h>
#include <mapviz/map_canvas.h>

// QT autogenerated files
#include "ui_marker_config.h"
#include "ui_topic_select.h"

namespace mapviz_plugins
{
  class TexturedMarkerPlugin : public mapviz::MapvizPlugin
  {
    Q_OBJECT

  public:
    TexturedMarkerPlugin();
    virtual ~TexturedMarkerPlugin();

    bool Initialize(QGLWidget* canvas);
    void Shutdown() {}

    void Draw(double x, double y, double scale);

    void Transform();

    void LoadConfig(const YAML::Node& node, const std::string& path);
    void SaveConfig(YAML::Emitter& emitter, const std::string& path);

    QWidget* GetConfigWidget(QWidget* parent);

  protected:
    void PrintError(const std::string& message);
    void PrintInfo(const std::string& message);
    void PrintWarning(const std::string& message);

  protected Q_SLOTS:
    void SelectTopic();
    void TopicEdited();

  private:
    struct MarkerData
    {
      ros::Time stamp;
      ros::Time expire_time;

      float alpha_;

      std::vector<uint8_t> texture_;
      int32_t texture_id_;
      int32_t texture_size_;
      float texture_x_;
      float texture_y_;
      
      std::string encoding_;
      
      std::vector<tf::Vector3> quad_;
      std::vector<tf::Vector3> transformed_quad_;
      
      bool transformed;
    };

    Ui::marker_config ui_;
    QWidget* config_widget_;

    std::string topic_;

    ros::Subscriber marker_sub_;
    bool has_message_;

    std::map<std::string, std::map<int, MarkerData> > markers_;

    bool is_marker_array_;

    void ProcessMarker(const marti_visualization_msgs::TexturedMarker& marker);

    void MarkerCallback(const marti_visualization_msgs::TexturedMarkerConstPtr marker);

    void MarkerArrayCallback(
      const marti_visualization_msgs::TexturedMarkerArrayConstPtr markers);
  };
}

#endif  // MAPVIZ_PLUGINS_TEXTURED_MARKER_PLUGIN_H_
