// *****************************************************************************
//
// Copyright (c) 2021, Trinity University
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of Southwest Research Institute® (SwRI®) nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// *****************************************************************************

#ifndef MAPVIZ_PLUGINS_FOLLOW_WAYPOINTS_PLUGIN_H_
#define MAPVIZ_PLUGINS_FOLLOW_WAYPOINTS_PLUGIN_H_

// Mapviz libraries
#include <mapviz/mapviz_plugin.h>

// ROS libraries
#include <ros/ros.h>
#include <std_msgs/Empty.h>
#include <actionlib_msgs/GoalID.h>

// QT libraries
#include <QGLWidget>

// QT autogenerated files
#include "ui_follow_waypoints_config.h"

/**
 * This plugin provides buttons to clear the current waypoint queue, start navigating that queue, and abort the current navigation queue.
 */
namespace mapviz_plugins
{
  class FollowWaypointsPlugin : public mapviz::MapvizPlugin
  {
    Q_OBJECT

   public:

    FollowWaypointsPlugin();
    virtual ~FollowWaypointsPlugin();

    bool Initialize(QGLWidget* canvas);
    void Shutdown() {}

    void Draw(double x, double y, double scale) {};

//    void Paint(QPainter* painter, double x, double y, double scale) {}
    void Transform() {};

    void LoadConfig(const YAML::Node& node, const std::string& path);
    void SaveConfig(YAML::Emitter& emitter, const std::string& path);

    QWidget* GetConfigWidget(QWidget* parent);

   protected:
    virtual void PrintError(const std::string& message) override;
    virtual void PrintInfo(const std::string& message) override;
    virtual void PrintWarning(const std::string& message) override;

  private Q_SLOTS:
    void on_pushButtonCancelNav_toggled(bool checked);
    void on_pushButtonClearQueue_toggled(bool checked);
    void on_pushButtonExecute_toggled(bool checked);

  private:
    Ui::follow_waypoints_config ui_;
    QWidget* config_widget_;
    ros::NodeHandle nh_;
  };
}

#endif // MAPVIZ_PLUGINS_FOLLOW_WAYPOINTS_PLUGIN_H_
