title: "Mapviz"
description: Modular ROS visualization tool for 2D data
baseurl: "/mapviz" # the subpath of your site, e.g. /blog
url: "https://swri-robotics.github.io" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: pmarsceill/just-the-docs

permalink: /:title/
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Mapviz on GitHub":
    - "//github.com/swri-robotics/mapviz"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2024 Southwest Research Institute. Distributed under the <a href=\"https://github.com/swri-robotics/mapviz/tree/master/LICENSE\">BSD 3-Clause license.</a>"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking:

plugins:
  - jekyll-seo-tag

collections:
  plugins:
    output: true

defaults:
  - scope:
      path: ''
      type: 'plugins'
    values:
      layout: 'plugin'
      parent: 'Plugins'

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

theme: jekyll-theme-cayman