#ifndef ODOMETRY_PLUGIN_H
#define ODOMETRY_PLUGIN_H

// C++ standard libraries
#include <string>
#include <list>

// QT libraries
#include <QGLWidget>
#include <QObject>
#include <QWidget>
#include <QColor>

// ROS libraries
#include <ros/ros.h>
#include <tf/transform_datatypes.h>
#include <nav_msgs/Odometry.h>

#include <mapviz/mapviz_plugin.h>
#include <mapviz/map_canvas.h>

// QT autogenerated files
#include "ui_odometry_config.h"
#include "ui_topic_select.h"

namespace mapviz_plugins
{

  class OdometryPlugin : public mapviz::MapvizPlugin
  {

    Q_OBJECT
  
  public:

    enum DrawStyle { LINES = 0, POINTS };

    OdometryPlugin();
    virtual ~OdometryPlugin();

    bool Initialize(QGLWidget* canvas);
    void Shutdown() {}
    
    void Draw(double x, double y, double scale);

    void Transform();
    
    void LoadConfiguration(const YAML::Node& node);
    void SaveConfiguration(YAML::Emitter& emitter);

    QWidget* GetConfigWidget(QWidget* parent);

  protected:
    void PrintError(const std::string& message);
    void PrintInfo(const std::string& message);
    void PrintWarning(const std::string& message);

  protected Q_SLOTS:
    void SelectTopic();
    void SelectColor();
    void TopicEdited();
    void PositionToleranceChanged(double value);
    void AngleToleranceChanged(double value);
    void BufferSizeChanged(int value);
    void SetDrawStyle(QString style);
    
  private:
    QGLWidget* canvas_;
  
    Ui::odometry_config ui_;
    QWidget* config_widget_;
    QColor color_;

    DrawStyle draw_style_;

    std::string topic_;

    tf::Point current_point_;
    tf::Point current_point_transformed_;

    int buffer_size_;
    float position_tolerance_;
    float angle_tolerance_;

    ros::Subscriber odometry_sub_;
    bool has_message_;

    std::list<tf::Point> points_;
    std::list<tf::Point> transformed_points_;

    void odometryCallback(const nav_msgs::OdometryConstPtr odometry);
  };
}

#endif /* ODOMETRY_PLUGIN_H */
