name: Lyrical (testing)

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {ROS_DISTRO: lyrical, ROS_REPO: testing, PIP_BREAK_SYSTEM_PACKAGES: True}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Refresh Ubuntu package indexes
        run: |
          sudo apt-get update \
            -o Acquire::Retries=3

      - uses: ros-industrial/industrial_ci@master
        env: ${{ matrix.env }}
